apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web2
  name: web2
spec:
  runtimeClassName: gvisor
  containers:
  - image: docker.io/library/httpd:2.4.58
    name: web2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
