apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitors-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visitors
      tier: frontend
  template:
    metadata:
      labels:
        app: visitors
        tier: frontend
    spec:
      containers:
      - name: visitors-frontend
        image: "schnell18/visitors-webui:1.0.0"
        imagePullPolicy: Always
        ports:
        - name: visitors
          containerPort: 3000
          protocol: TCP
        env:
        - name: REACT_APP_TITLE
          value: "Visitors Dashboard"
