---
# tasks file for etcd

- name: create etcd group
  group:
    name: etcd
    state: present
- name: create etcd user
  user:
    name: etcd
    shell: /bin/false
    home: /var/lib/etcd
    group: etcd
    create_home: True
    state: present
- name: ensure /var/lib/etcd/default exists
  file:
    path: /var/lib/etcd/default
    state: directory
    owner: etcd
    group: etcd
    mode: 0755


# download etcd binaries
- name: test if etcd binaries are downloaded
  stat:
    path: /work/.preload/etcd
  register: pmkb
- name: download etcd binaries
  shell: "{{ lookup('template', 'download-etcd.sh') }}"
  args:
    executable: /bin/bash
  when: "pmkb.stat.exists == False"

- name: test if etcd binaries are installed
  stat:
    path: /usr/local/bin/etcd
  register: pmk
- name: install etcd binaries
  shell: "{{ lookup('template', 'install-etcd.sh') }}"
  args:
    executable: /bin/bash
  when: "pmk.stat.exists == False"

- name: test if etcd kubernetes client certificate is genereated
  stat:
    path: /var/lib/etcd/default/etcd-kube-client.pem
  register: cert
- name: generate etcd kubernetes client certificate
  shell: "{{ lookup('template', 'gen-etcd-kube-client-cert.sh') }}"
  args:
    executable: /bin/bash
  when: "cert.stat.exists == False"

- name: prepare config file
  template:
    src: etcd.yml.j2
    dest: /var/lib/etcd/default/etcd.yml
    owner: etcd
    group: etcd
    mode: 0644
  notify: restart etcd

- name: prepare systemd unit file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: 0644
  notify: restart etcd

# run the queued handlers immediately
- meta: flush_handlers

- name: config etcdctl for root
  lineinfile:
    path: /root/.bashrc
    create: True
    regexp: "{{ item.regexp1 }}"
    line: "{{ item.replace }}"
    state: present
  with_items:
    - { regexp1: '^export ETCDCTL_ENDPOINTS=.*$', replace: 'export ETCDCTL_ENDPOINTS=https://localhost:2379'}
    - { regexp1: '^export ETCDCTL_API=.*$', replace: 'export ETCDCTL_API=3'}
    - { regexp1: '^export ETCDCTL_CACERT=.*$', replace: 'export ETCDCTL_CACERT={{ sys_share_ca_dir }}/ownca.crt'}
    - { regexp1: '^export ETCDCTL_CERT.*$', replace: 'export ETCDCTL_CERT={{ etcd_data_dir }}/default/etcd-kube-client.pem'}
    - { regexp1: '^export ETCDCTL_KEY.*$', replace: 'export ETCDCTL_KEY={{ etcd_data_dir }}/default/etcd-kube-client-key.pem'}