---
# defaults file for kube-master
cluster_name: my-kube
kube_data_dir: /var/lib/kubernetes
internal_ip: 192.168.90.15 
kubernetes_public_address: 192.168.90.15 
temp_data_dir: /tmp
ownca_cn: kubernetes
ownca_c: CN
ownca_st: Shanghai
ownca_l: Shanghai
ownca_o: earthling
ownca_ou: jjhome
ownca_key_size: 4096
ownca_expiry: 8760h
apiserver_ou: jjhome
kube_scheduler_ou: jjhome
kube_proxy_ou: jjhome
kube_admin_cn: admin
kube_admin_o: system:masters
kube_admin_ou: jjhome
service_account_cn: service-accounts
service_account_o: kubernetes
service_account_ou: jjhome
kube_controller_manager_ou: jjhome
sys_share_ca_dir: /usr/local/share/ca-certificates/jjhome