kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: kbm1.kube.vn
    path: /var/nfs/task
