apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "registry.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/registry-configmap.yaml") . | sha256sum }}
  labels:
    name: {{ template "registry.fullname" . }}
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.registry.replicas }}
  selector:
    matchLabels:
      name: {{ template "registry.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "registry.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "registry.fullname" . }}
          image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}"
          imagePullPolicy: {{ .Values.registry.image.pullPolicy }}
          {{- if .Values.portus.tls.enabled }}
          command: ["/bin/sh"]
          args: ["-c", "cp /certificates/ca-certs.crt /usr/local/share/ca-certificates;update-ca-certificates;registry serve /etc/docker/registry/config.yml"]
          {{- end }}
          ports:
            - containerPort: {{ .Values.registry.service.port }}
            - containerPort: {{ .Values.registry.service.debugPort }}
          resources:
{{ toYaml .Values.registry.resources | indent 12 }}
          volumeMounts:
            {{- if .Values.portus.tls.enabled }}
            - name: certvol
              mountPath: /certificates
            {{- end }}
            - name: config
              mountPath: /etc/docker/registry
              readOnly: true
            - name: storage
              mountPath: {{ .Values.registry.mountPath }}
      volumes:
        {{- if .Values.portus.tls.enabled }}
        - name: certvol
          secret:
            secretName: {{ template "portus.fullname" . }}
            items:
            - key: key
              path: portus.key
            - key: cert
              path: portus.crt
            - key: ca
              path: ca-certs.crt
        {{- end }}
        - name: config
          configMap:
            name: {{ template "registry.fullname" . }}
            items:
              - key: config
                path: config.yml
        - name: storage
          {{- if .Values.registry.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "registry.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
