apiVersion: v1
kind: Service
metadata:
  name: titra-service
  labels:
    name: titra
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32070
  selector:
    app: titra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titra
  labels:
    app: titra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titra
  template:
    metadata:
      labels:
        app: titra
    spec:
      containers:
      - name: titra
        image: docker.io/kromit/titra:0.79.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MONGO_URL
          value: "mongodb://titra:titra@mongod-0.mongodb-service,mongod-1.mongodb-service,mongod-2.mongodb-service/titra?authSource=titra&replicaSet=MainRepSet"
        - name: ROOT_URL
          value: "http://titra.kube.vn:32070"
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
