# https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta3#ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: kubernetes
controlPlaneEndpoint: "{{ kubernetes_public_address }}:6443"
kubernetesVersion: v{{ kubernetes_version }}
apiServer:
  certSANs:
  - "{{ kubernetes_public_address }}"
  extraArgs:
    enable-admission-plugins: "{% for plugin in admission_plugins %}{{ plugin }}{% if not loop.last %},{% endif %}{% endfor %}"
    advertise-address: {{ kubernetes_public_address }}
networking:
  podSubnet: "{{ pod_cidr }}"
controllerManager:
  extraArgs:
    # auto-create secret for service account to be compatible w/ previous releases
    feature-gates: LegacyServiceAccountTokenNoAutoGeneration=false
