apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: frontend
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 250m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web1
  name: web1
  namespace: frontend
spec:
  containers:
  - image: docker.io/library/nginx:1.24.0-bullseye-perl
    name: web1
    resources: {}
