apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web2
  name: web2
  namespace: backend
spec:
  containers:
  - image: docker.io/library/nginx:1.24.0-bullseye-perl
    name: web2
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "400Mi"
        cpu: "400m"
