---
# defaults file for kube-node
kube_conf_dir: /etc/kubernetes
# google_apt_mirror: http://newton:8081/repository/kubernetes/
# buster_apt_mirror: http://newton:8081/repository/buster/
# google_apt_mirror: https://apt.bbvk18.cf/
# google_apt_mirror: https://mirrors.aliyun.com/kubernetes/apt/
# google_apt_mirror_apt_key: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
kubernetes_apt_mirror: "https://pkgs.k8s.io/core:/stable:"
hypervisor: libvirt
discovery_directory: /mnt/disks
disk_additional_disks_libvirt:
- device: /dev/vdb
  disk: disk1
  fstype: ext4
  partitions: 10
- device: /dev/vdc
  disk: disk2
  fstype: ext4
  partitions:  5

disk_additional_disks:
- device: /dev/sdb
  disk: disk1
  fstype: ext4
  partitions: 10
- device: /dev/sdc
  disk: disk2
  fstype: ext4
  partitions:  5
