---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: no-access-rb
subjects:
- kind: ServiceAccount
  name: no-access-sa
  namespace: dev
roleRef:
  kind: ClusterRole
  name: no-access-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-access-rb
subjects:
- kind: ServiceAccount
  name: secret-access-sa
  namespace: dev
roleRef:
  kind: ClusterRole
  name: secret-access-cr
  apiGroup: rbac.authorization.k8s.io

