---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: no-access-cr
rules:
  - apiGroups: [""]
    resources: [""]
    verbs: [""]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-access-cr
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
