---
apiVersion: v1
kind: Pod
metadata:
  name: no-access-pod
spec:
  serviceAccountName: no-access-sa
  containers:
  - name: no-access-container
    image: docker.io/pajk_dev/sademo
    imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-access-pod
spec:
  serviceAccountName: secret-access-sa
  containers:
  - name: secret-access-container
    image: docker.io/pajk_dev/sademo
    imagePullPolicy: IfNotPresent
