---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: no-access-rb
  namespace: dev
subjects:
- kind: ServiceAccount
  name: no-access-sa
roleRef:
  kind: Role
  name: no-access-r
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-access-rb
  namespace: dev
subjects:
- kind: ServiceAccount
  name: secret-access-sa
roleRef:
  kind: Role
  name: secret-access-r
  apiGroup: rbac.authorization.k8s.io

