---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: no-access-r
rules:
  - apiGroups: [""]
    resources: [""]
    verbs: [""]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: secret-access-r
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
