apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ping
  name: ping
spec:
  containers:
  - name: ping
    command:
    - sh
    - -c
    - ping google.com
    image: docker.io/library/bash:5
  - name: proxy
    image: docker.io/library/ubuntu:noble
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
    command:
    - sh
    - -c
    - 'apt-get update && apt-get install -y iptables && iptables -L && sleep 1d'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
