---
- hosts: node
  become: true
  pre_tasks:
    # install and config tsocks
    - name: install tsocks
      apt:
        name: tsocks
        state: present
    - name: config tsocks
      replace:
        path: /etc/tsocks.conf
        regexp: '^server = 192.168.0.1$'
        replace: 'server = 10.0.2.2'

    - name: Make sure /var/lib/data exists
      file:
        path: /var/lib/data
        state: directory

    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: no
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

  roles:
    - role: docker
    - role: kube-node

- hosts: master
  roles:
    - role: kube-dashboard