---
- hosts: node
  become: true
  pre_tasks:

    - name: Make sure /var/lib/data exists
      file:
        path: /var/lib/data
        state: directory

    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

  roles:
    - role: docker
    - role: kube-node