---
- hosts: node
  vars:
    kubernetes_version: "1.18.0"
    kubernetes_gcr_repository: "gcr.azk8s.cn"

  become: true
  pre_tasks:

    - name: Install disk management packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - parted

  roles:
    - role: docker
    - role: kube-node
