apiVersion: v1
kind: Secret
metadata:
  name: projected-secret
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi
---
apiVersion: v1
kind: Pod
metadata:
  name: projected-secret-pod
spec:
  containers:
  - name: projected-secret-pod
    image: docker.io/library/busybox:1.28
    command:
    - sh
    - -c
    - "echo 'Gutten Tag' && find /etc/foo/ && sleep 1d"
    volumeMounts:
      - name: foo
        mountPath: "/etc/foo"
        readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: projected-secret
      items:
      - key: username
        path: my-group/my-username
