---
# tasks file for docker

- name: Add an apt signing key for Docker
  apt_key:
    data: "{{ lookup('file', 'docker-apt-key.asc') }}"
    state: present

- name: Add docker stable apt repository
  apt_repository:
    repo: deb [arch=amd64] {{ docker_apt_mirror }} buster stable
    state: present
    filename: docker

- name: Install docker and its dependecies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify:
    - Restart docker

- name: Add devel user to docker group
  user:
    name: devel
    group: docker

- name: Make sure /etc/docker exists
  file:
    path: /etc/docker
    state: directory
- name: Add docker registry mirrors
  copy:
    content: "{{ lookup('template', 'daemon.json') }}"
    mode: 0755
    dest: /etc/docker/daemon.json
  when: enable_docker_registry_mirrors == True
  notify:
    - Restart docker

- meta: flush_handlers