apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: noop-shell
  name: noop-shell
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - args:
    - sh
    - -c
    - sleep 1d
    image: docker.io/library/busybox
    name: noop-shell
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
