---
# tasks file for kube-node

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: "{{ kubernetes_apt_mirror }}/v{{ kubernetes_version }}/deb/Release.key"
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: "deb {{ kubernetes_apt_mirror }}/v{{ kubernetes_version }}/deb/ /"
    state: present
    filename: kubernetes
    update_cache: yes

- name: Install Kubernetes binaries
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: no
  vars:
    packages:
      - kubelet={{ kubernetes_version }}.{{ kubernetes_patch }}-{{ kubernetes_pkg_rev }}
      - kubeadm={{ kubernetes_version }}.{{ kubernetes_patch }}-{{ kubernetes_pkg_rev }}
      - kubectl={{ kubernetes_version }}.{{ kubernetes_patch }}-{{ kubernetes_pkg_rev }}

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    state: present
    create: yes
    line: KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --node-ip={{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}
  notify:
    - Restart kubelet

- meta: flush_handlers

- name: Prepare partitions for additional disks on VirtualBox backend
  shell: "{{ lookup('template', 'prepare-partitions.sh') }}"
  args:
    executable: /bin/bash
  register: clpp
  with_items: "{{ disk_additional_disks }}"
  changed_when: "'Prepared partitions' in clpp.stdout"
  when: hypervisor != 'libvirt'
  tags: ['disk', 'partition']

- name: Prepare partitions for additional disks on libvirt backend
  shell: "{{ lookup('template', 'prepare-partitions.sh') }}"
  args:
    executable: /bin/bash
  register: clpp
  with_items: "{{ disk_additional_disks_libvirt }}"
  changed_when: "'Prepared partitions' in clpp.stdout"
  when: hypervisor == 'libvirt'
  tags: ['disk', 'partition']

# - name: load meta images if absent
#   shell: "{{ lookup('template', 'load-k8s-meta-images.sh') }}"
#   args:
#     executable: /bin/bash
#   register: kbgn
#   changed_when: "'Loaded k8s meta images' in kbgn.stdout"

# test existence of /etc/kubernetes/kubelet.conf to avoid repeated join
- name: Test if node already joins cluster
  stat:
    path: "{{ kube_conf_dir }}/kubelet.conf"
  register: jstat

- name: Wait until the join-command.sh is available
  ansible.builtin.wait_for:
    path: /work/.preload/join-command.sh
  when: jstat.stat.exists == False

- name: Join the node to cluster
  command: sh /work/.preload/join-command.sh
  when: jstat.stat.exists == False

- name: Harden kubelet config file permission
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '600'
  with_items:
    - /var/lib/kubelet/config.yaml
    - /lib/systemd/system/kubelet.service
