IMAGE_NAME = "generic/debian12"
IMAGE_VERSION = "4.3.10"
NODES = 4
EXTRA_DISKS = 2
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'


Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_keys/vagrant.key.rsa"]
    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/work", automount: true, SharedFoldersEnableSymlinksCreate: false

    # take care of /etc/hosts in both host and guest
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true

    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.box_version = IMAGE_VERSION
        master.vm.network "private_network", ip: "192.168.122.10"
        master.vm.hostname = "master"
        master.vm.provision :hostmanager
        master.hostmanager.aliases = %w(master.kube.vn)

        master.vm.provider "libvirt" do |v|
            # the default pool is full
            v.storage_pool_name = "home-pool"
            v.title = "master"
            v.description = "Kubernetes Master"
            v.memory = 2048
            v.cpus = 4
        end

        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "provision/playbook-master.yml"
        end
    end

    (1..NODES).each do |i|
        node_id = "slave-#{i}"
        config.vm.define node_id do |slave|
            slave.vm.box = IMAGE_NAME
            slave.vm.box_version = IMAGE_VERSION
            slave.vm.network "private_network", ip: "192.168.122.#{i + 10}"
            slave.vm.hostname = node_id
            slave.vm.provision :hostmanager
            slave.hostmanager.aliases = "#{node_id}.kube.vn"
    
            slave.vm.provider "libvirt" do |v|
                v.title = node_id
                v.memory = 2048
                v.cpus = 2
                (1..EXTRA_DISKS).each do |j|
                    v.storage :file, :size => '30G'
                end
            end
    
            slave.vm.provision "ansible" do |ansible|
                ansible.playbook = "provision/playbook-node.yml"
                ansible.config_file = "provision/ansible.cfg"
            end
        end
    end
end

# vim:set nu ai expandtab sw=4 ts=4 syntax=ruby:
