Vagrant.configure(2) do |config|

  config.vm.box = "debian98-min"
  config.vm.box_check_update = false
  config.rdp.port = 5000
  config.vm.synced_folder ".", "/work", automount: true

  # take care of /etc/hosts in both host and guest
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  # provision master
  1.times do |i|
    node_id = "kbm#{i + 1}"
    config.vm.define node_id do |kbm|
      kbm.vm.network "private_network", ip: "192.168.90.1#{i + 5}"
      kbm.vm.provision :hostmanager
      kbm.hostmanager.aliases = %w(kbm1.kube.vn)
      kbm.vm.hostname = "#{node_id}.kube.vn"
      kbm.vm.provider "virtualbox" do |vb|
        vb.name   = node_id
        vb.gui    = false
        vb.memory = 1024
        vb.cpus   = 2
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
    end
  end

  # provision nodes
  3.times do |i|
    node_id = "kbn#{i + 1}"
    ip = "192.168.90.2#{i + 5}"
    config.vm.define node_id do |kbn|
      kbn.vm.network "private_network", ip: ip
      kbn.vm.provision :hostmanager
      kbn.vm.hostname = "#{node_id}.kube.vn"
      kbn.hostmanager.aliases = %W(kbn#{i + 1}.kube.vn)
      kbn.vm.provider "virtualbox" do |vb|
        vb.name   = node_id
        vb.gui    = false
        vb.memory = 1024
        vb.cpus   = 2
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
    end
  end

end

# vim: set ai nu nobk expandtab sw=2 tw=72 ts=4 syntax=ruby :
