apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: web-layer
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        version: "2"
    spec:
      containers:
        - name: nginx
          image: nginx
