apiVersion: v1
kind: Pod
metadata:
  name: audit-pod
  labels:
    app: audit-pod
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/audit.json
  containers:
  - name: audit-container
    image: docker.io/library/nginx:1.24.0-bullseye-perl
    securityContext:
      allowPrivilegeEscalation: false
