apiVersion: v1
kind: Pod
metadata:
  name: finegrained-pod
  labels:
    app: finegrained-pod
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/fine-grained.json
  containers:
  - name: finegrained-container
    image: hashicorp/http-echo:1.0
    # image: docker.io/library/nginx:1.24.0-bullseye-perl
    args:
    - "-text=just made some syscalls!"
    securityContext:
      allowPrivilegeEscalation: false
