apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-redis
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/redis
    server: 192.168.90.15
