apiVersion: v1
kind: Pod
metadata:
  name: shell007
spec:
  containers:
  - name: shell007
    image: busybox:latest
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "trap: TERM INT; while true; do echo 'K8S rocks!!!'; sleep 1; done" ]

