Vagrant.configure(2) do |config|

  config.vm.box = "centos66-java8-dev"
  config.vm.box_check_update = false
  config.rdp.port = 5000
  config.vm.synced_folder ".", "/work"

  # take care of /etc/hosts in both host and guest
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

$script1 = <<SCRIPT1
rpm -q --queryformat "%{name} %{version} installed" zookeeper
if [[  $? != 0 ]]; then
  yum localinstall -y /tmp/zookeeper-3.4.8-1.el6.x86_64.rpm
fi
if [[ -z $(grep server.1 /etc/zookeeper/zoo.cfg) ]]; then
cat <<'EOF' >> /etc/zookeeper/zoo.cfg

## workaround leader election port is opened only on loopback NIC
quorumListenOnAllIPs=true

########## cluster definition start ##########
server.1=kf1.kafka.vn:2888:3888
server.2=kf2.kafka.vn:2888:3888
server.3=kf3.kafka.vn:2888:3888
########## cluster definition end ##########
EOF
fi
echo $MYID > /var/lib/zookeeper/data/myid
chkconfig --level 345 zookeeper on
service zookeeper start

SCRIPT1

# install kafka
$script2 = <<SCRIPT2
rpm -q --queryformat "%{name} %{version} installed" kafka
if [[  $? != 0 ]]; then
  yum localinstall -y /tmp/kafka-0.10.1.0-1.el6.x86_64.rpm
fi

echo sed -i "'s|\\(broker.id\\)=.*|\\1=$MYID|'" /var/lib/kafka/config/server.properties | sh
echo sed -i "'s|\\(zookeeper.connect\\)=.*|\\1=$ZK_HOSTS|'" /var/lib/kafka/config/server.properties | sh
echo sed -i "'s|#\\(advertised.listeners\\)=.*|\\1=PLAINTEXT://${KF_HOST}:9092|'" /var/lib/kafka/config/server.properties | sh

echo 'KAFKA_HEAP_OPTS="-Xmx512M -Xms512M"' > /etc/sysconfig/kafka
chkconfig --level 345 kafka on
service kafka start
SCRIPT2

  zk_hosts = (1..3).to_a.map{|i| "kf#{i}.kafka.vn:2181"}.join(",")

  3.times do |i|
    node_id = "kf#{i + 1}"
    config.vm.define node_id do |kf|
      config.vm.provision "file", source: ".vagrant_prov/zookeeper-3.4.8-1.el6.x86_64.rpm", destination: "/tmp/zookeeper-3.4.8-1.el6.x86_64.rpm"
      config.vm.provision "file", source: ".vagrant_prov/kafka-0.10.1.0-1.el6.x86_64.rpm", destination: "/tmp/kafka-0.10.1.0-1.el6.x86_64.rpm"
      kf.vm.provision "shell", inline: $script1, env: {:MYID => i + 1}
      kf.vm.provision "shell", inline: $script2, env: {:MYID => i + 1, :ZK_HOSTS => zk_hosts, :KF_HOST => "kf#{i + 1}.kafka.vn"}
      kf.vm.network "private_network", ip: "192.168.81.1#{i + 5}"
      kf.vm.hostname = "kf#{i + 1}.kafka.vn"
      kf.vm.provision :hostmanager
      kf.vm.provider "virtualbox" do |vb|
        vb.name   = node_id
        vb.gui    = false
        vb.memory = 1024
        vb.cpus   = 2
      end
    end
  end

end

# vim: set ai nu nobk expandtab sw=2 tw=72 ts=4 syntax=ruby :
