---
# tasks file for docker

- name: Add docker official yum repository
  yum_repository:
    name: docker-ce-stable
    description: Docker official repository
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker and its dependecies
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify:
    - Restart docker

- name: Add devel user to docker group
  user:
    name: devel
    group: docker

- name: Make sure /etc/docker exists
  file:
    path: /etc/docker
    state: directory
- name: Add docker registry mirrors
  copy:
    content: "{{ lookup('template', 'daemon.json') }}"
    mode: 0755
    dest: /etc/docker/daemon.json
  when: enable_docker_registry_mirrors == True
  notify:
    - Restart docker

- meta: flush_handlers
