---
# tasks file for faclo

- name: Add an apt signing key for Falco
  apt_key:
    data: "{{ lookup('file', 'falco-apt-key.asc') }}"
    state: present

- name: Add Falco stable apt repository
  apt_repository:
    repo: deb [arch=amd64] {{ falco_apt_mirror }} stable main
    state: present
    filename: falco

- name: Install falco and dependecies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - dkms
    - make
    - "linux-headers-{{ ansible_kernel }}"
    - falco
  environment:
      FALCO_FRONTEND: noninteractive

- name: Compile Falco kmod
  shell: "{{ lookup('template', 'compile-falco-kmod.sh') }}"
  args:
    executable: /bin/bash
  register: cbgn
  changed_when: "'Compiled falco kmod' in cbgn.stdout"

- name: Enable falco-kmod
  ansible.builtin.systemd_service:
    name: falco-kmod
    enabled: true
    daemon_reload: yes
    state: started
