kind: ConfigMap
apiVersion: v1
metadata:
  name: registry-config
  namespace: kube-system
data:
  htpassword: |-
    bitmover:$2y$05$h3F6w4V6DRDZd7g0cPI8AeO/W8RBwAh5iHn/r17yaicjaVA0feCx2
  # The CNI network configuration to install on each node.
  config.yml: |-
    version: 0.1
    storage:
    filesystem:
        rootdirectory: /var/lib/registry
        maxthreads: 100
    delete:
        enabled: false
    redirect:
        disable: false
    maintenance:
        uploadpurging:
            enabled: true
            age: 168h
            interval: 24h
            dryrun: false
            readonly:
                enabled: false
    auth:
        htpasswd:
            realm: jjhome-docker-registry-auth
            path: /etc/registry/htpasswd

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry2
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry2
    spec:
      containers:
      - name: registry2
        image: registry:2
        imagePullPolicy: IfNotPresent
        env:
          - name: REGISTRY_HTTP_ADDR
            value: 0.0.0.0:443
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: /certs/etcd-cert
          - name: REGISTRY_HTTP_TLS_KEY
            value: /certs/etcd-key
        volumeMounts:
        - mountPath: /certs
          name: certs-conf
        - mountPath: /etc/registry/
          name: htpasswd-conf
      volumes:
      - name: certs-conf
        secret:
          secretName: calico-etcd-secrets
      - name: registry-conf
        configMap:
          name: registry-config
